services:
  mozhi:
    image: codeberg.org/aryak/mozhi:latest
    restart: unless-stopped
    ports:
      - "54318:3000"
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/version || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600