services:

  cobalt-web:
    build:
      context: ../..
      dockerfile: services/cobalt/Dockerfile-web
      args:
        - WEB_URL=frontendCHANGEME
        - WEB_DEFAULT_API=backendCHANGEME
    restart: unless-stopped
    container_name: cobalt-web
    init: true
    ports:
      - 54311:8080/tcp
      
  cobalt-api:
    image: ghcr.io/imputnet/cobalt:10
    restart: unless-stopped
    container_name: cobalt-api
    init: true
    ports:
      - 54312:9000/tcp
    environment:
      - API_PORT=9000
      - API_URL=backendCHANGEME
      - API_NAME=nameCHANGEME
      - COOKIE_PATH=/cookies.json
    labels:
      - com.centurylinklabs.watchtower.scope=cobalt-api
    volumes:
      - ./cookies.json:/cookies.json

  watchtower:
    image: ghcr.io/containrrr/watchtower
    restart: unless-stopped
    command: --cleanup --scope cobalt-api --interval 3600
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    enable_ipv6: true
    ipam:
      config:
        - subnet: fd01:db8:c::/64
          gateway: fd01:db8:c::1
